export const UI_START_LOADING_CATEGORIES = 'ui/ START LOADING CATEGORIES';
export const UI_FINISH_LOADING_CATEGORIES = 'ui/ FINISH LOADING CATEGORIES';
export const UI_ERROR_LOADING_CATEGORIES = 'ui/ ERROR LOADING CATEGORIES';
export const UI_START_SUBMITTING_QUESTION = 'ui/ START SUBMITTING QUESTION';
export const UI_FINISH_SUBMITTING_QUESTION = 'ui/ FINISH SUBMITTING QUESTION';
export const UI_ERROR_SUBMITTING_QUESTION = 'ui/ ERROR SUBMITTING QUESTION';