export const START_LOADING_STATS = 'ui/ START LOADING STATS';
export const FINISH_LOADING_STATS = 'ui/ FINISH LOADING STATS';
export const FAIL_LOADING_STATS = 'ui/ FAIL LOADING STATS';
export const SELECT_MODE = 'ui/ SELECT GAME STATS MODE';
export const SELECT_DIFFICULTY = 'ui/ SELECT GAME STATS DIFFICULTY';
