export const UI_START_LOADING_QUESTIONS = 'ui/ START LOADING QUESTIONS';
export const UI_FINISH_LOADING_QUESTIONS = 'ui/ FINISH LOADING QUESTIONS';
export const UI_FAIL_LOADING_QUESTIONS = 'ui/ FAIL LOADING QUESTIONS';
